### ISSUE TITLE
include license file

### ISSUE THREAD

**Issue by humane-barry** [monatis/clip.cpp#21]
Many companies require a permissive license to allow use of open-source code (typically MIT or Apache2).  Some projects wish to restrict use to research or personal (often with Creative Commons BY-NC-SA).  For what it's worth, [ggml](https://github.com/ggerganov/ggml/blob/d2cd00f8b762bf5ee8f8bd3a13866f1990aadad6/LICENSE) uses the commercial-friendly MIT license.

Would you mind adding a license file that fits with your goals for the project?  That clarity would be greatly appreciated.

**Comment by humane-barry** [comment]
Full disclosure: I am with a company that is interested in including your software in our project.  We would obviously prefer a commercial license but will respect your decision.

**Comment by monatis** [comment]
Hi @humane-barry, thanks for the issue. I am happy to hear that you consider including it in your project, so added the MIT license file. It is the most permissive license I'm aware of.

I'd like to give it a try if you don't mind letting me know wen your product is released. Best of the luck!

**Comment by humane-barry** [comment]
Thank you for the license, and also so so much for your contribution to the AI community.
