### ISSUE TITLE
Can this use convNeXt architecture? 

### ISSUE THREAD

**Issue by JianbangZ** [monatis/clip.cpp#29]
As I last checked, ggml supports CONV_2D, so it should work? or even expand to any tranditional CNN like resnet?

**Comment by monatis** [comment]
Unfortunately not yet. Currently this implements only ViT architecture. GGML's support for convolutions is currently limited, and as I implement more models I'd like to contribute back to GGML. I have a few architectures in mind to implement after CLIP, but community demand is also important.

**Comment by JianbangZ** [comment]
Thanks.
I think ggml is proven to be very efficient in the LLM inference, I see no reasons it doesn't do well in the CV world, plus the quantization is quite handy. k-quant is even better yet that's specific to transformers.
Do you have any local test data avaialble on the inference speed comparison between torch&CUDA vs clip.cpp &cuBLAS on the same ViT architecture?

**Comment by monatis** [comment]
> I see no reasons it doesn't do well in the CV world, 

Sure, what I meant was convolution operations in GGML currently have fixed kernel sizes / strides. We need to figure out a way of implementing generic convolutions, then implementing any convolution-based model should be straightforward. Luckily, ViT models usually use a single type of convolution operation and the rest is plain transformer blocks. But traditional models such as ResNet have a very rich set of convolution ops.

I implemented [a benchmarking utility](https://github.com/monatis/clip.cpp/blob/main/tests/benchmark.cpp) to measure the zero-shot labeling performance with acc@1 and acc@5 metrics as well as inference time, but haven't done a full comparison with Pytorch --I'm trying to decide on a good test set. I'm also currently working on batch inference support, maybe it would be more appropriate to include single-instance and batch inference performances in benchmarking.

**Comment by LeonNerd** [comment]
> Unfortunately not yet. Currently this implements only ViT architecture. GGML's support for convolutions is currently limited, and as I implement more models I'd like to contribute back to GGML. I have a few architectures in mind to implement after CLIP, but community demand is also important.

so,How's it going now?How's it going now?I came here from stable diffusion.cpp, ggml_conv_2d caused sd to not run on gpu.Its optimization needs some inspiration
