### ISSUE TITLE
Support custom mean-std normalization

### ISSUE THREAD

**Issue by monatis** [monatis/clip.cpp#32]
Some LAION checkpoints, the large variant for example, use different mean and std values for image normalization. Figure out a way to, preferably, encode what values to use, or introduce another funcion to preprocess with these values.

**Comment by Green-Sky** [comment]
yay, more hyper parameters
cant wait for gguf

**Comment by monatis** [comment]
Yes, another issue is, there seems to be no programatic way to infer what values to use apart from the notes in open-clip's readme. So I'm afraid we need to leave it to the user to specify whether to use custom mean-std values with a flag when converting models. Maybe a better way?

**Comment by monatis** [comment]
Released in #75
