### ISSUE TITLE
Segmentation Fault and Core Dump when running image-search-build with Multiple images in folder Using the 4bit model

### ISSUE THREAD

**Issue by GoYiz** [monatis/clip.cpp#45]
**Issue Description:**

When running the `image-search-build` command with a folder containing more than one image, it results in a segmentation fault and core dump.

**Problem Description:**

Running the `image-search-build` command crashes with a segmentation fault when the specified image folder contains more than one image. This issue occurs only when there are multiple images in the folder, while it works fine with a single image.

**Steps to Reproduce:**

1. Prepare a folder containing multiple images.
2. Run the following command:
```
$ bin/image-search-build -m ../models/laion_clip-vit-b-32-laion2b-s34b-b79k.ggmlv0.q4_1.bin ../tests

clip_model_load: loading model from '../models/laion_clip-vit-b-32-laion2b-s34b-b79k.ggmlv0.q4_1.bin' - please wait....................................................clip_model_load: model size =    93.92 MB / num tensors = 397
clip_model_load: model loaded
main: starting base dir scan of '../tests'
main: processing 2 files in 'tests'
.Segmentation fault (core dumped)
```

**Expected Behavior:**

The program should handle folders with multiple images correctly and generate the expected output.

**Actual Behavior:**

The program crashes with a segmentation fault when processing a folder with multiple images, resulting in a core dump.

**Additional Information:**

- I have attempted the following troubleshooting steps, but none have resolved the issue:
  - Ensuring correct file paths and contents.
  - Checking memory usage, ensuring sufficient available memory.
- I have also tried different image folders and model files, but the problem persists.
- The program works fine with a single image in the folder; the issue only arises when there are multiple images.

**Environment Information:**

- Operating System: Ubuntu 20.04
- RAM: 16G

Your help and support in addressing this matter would be greatly appreciated. Thank you!

**Comment by monatis** [comment]
I couldn't reproduce this issue on the latest master. Is your branch up-to-date?

**Comment by monatis** [comment]
Additionally, does it happen with f16-bit models? May be a memory issue with 4-bit quantized models.

**Comment by GoYiz** [comment]
Yeah, you are correct. After testing, I found that the f16bit model works fine, while the bug occurs only when running `image-search-build` with multiple images in a folder using the 4bit model.

**Comment by monatis** [comment]
Good, it should be regarding the increased mem requirement for batch inference of multiple images. Will patch it soon.
