### ISSUE TITLE
Can the text-encoder / vision-encoder be optional rather than mandatory?

### ISSUE THREAD

**Issue by josephilome** [monatis/clip.cpp#49]
There are times that, we only need half of CLIP, such as when a Vision Model is connected to an LLM after conversion, or when a Text Model provides guidance for Diffusion.

**Comment by monatis** [comment]
Yes, this is also a common use case for indexing with the image encoder and searching with the text encoder. The new GGUF format makes working with multiple formats easy so this will be handled when upgrading to the GGUF format.

**Comment by monatis** [comment]
Released in #75
