### ISSUE TITLE
bug: missing clip_free() in example/main.cpp

### ISSUE THREAD

**Issue by Green-Sky** [monatis/clip.cpp#6]
which causes the model to leak.

**Comment by monatis** [comment]
Ah yes. Patch in the latest commit, which riginally targets level of verbosity in `clip_model_load` function. It now accepts one extra parameter as an integer to control the amount of verbose prints.

**Comment by monatis** [comment]
I also want to support text-only and image-only model options in addition to the current one that contains both towers. My initial idea is to modify the conversion script to output text-only, image-only or two-tower models, and then modify `clip_model_load` (again introducing an extra param, sorry :D ) to specify the type of the model. Does it makes sense to you? Or any other suggestions?

**Comment by Green-Sky** [comment]
> I also want to support text-only and image-only model options in addition to the current one that contains both towers.
> My initial idea is to modify the conversion script to output text-only, image-only or two-tower models, and then modify clip_model_load (again introducing an extra param, sorry :D ) to specify the type of the model. Does it makes sense to you? Or any other suggestions?

what if they where totally separated? so 2 model files, 2 `model_load()` functions... hmm
I feel like that would be bad usability wise, since it could lead to non-aligned model mixups. But fundamentally yes.
