### ISSUE TITLE
Migrate to GGUF

### ISSUE THREAD

**Issue by monatis** [monatis/clip.cpp#60]
This will also resolve #32 and #49

**Comment by Happenedtostumblein** [comment]
Hi @monatis! Someone over at www.github.com/leejet/stable-diffusion.cpp suggested that maybe you’d want to help enable GPU acceleration for that repo. Would you be interested?

Sorry to ping you in this thread, but don’t know how else to get in touch!

**Comment by monatis** [comment]
Hi @Happenedtostumblein thanks for reaching out!. GPU support requires to implement conv2d op for CUDA that would be something clip.cpp also benefits from. It's in my TODO list, but the time I can devote to these projects may be limited from time to time due to contractual work I'm doing to make some money. I still hope to devote more time to accelerate development of these projects.

**Comment by Happenedtostumblein** [comment]
Hey Yusif!

Would you mind elaborating on what exactly makes it time-consuming or is merely outlining the work laborious in itself?

If you’re able to provide me with a 1,2,3 list of steps and goals, perhaps I can do it. I’m pretty good with numbers and math, but don’t speak cpp.

If it’s just not that simple, please excuse my ignorance and thank you again for your time and contributions :)

**Comment by FSSRepo** [comment]
@Happenedtostumblein Programming for CUDA requires you to know how to parallelize calculations, implement a kernel for conv2d, and, above all, support different data types (quantized and full integers).
