### ISSUE TITLE
Support batch inference for models other than patch32

### ISSUE THREAD

**Issue by skirodev** [monatis/clip.cpp#67]
The current batch inference code is only applicable to the patch32 model. When using other models such as patch16 or patch14, it produces incorrect results. Specifically, the behavior is such that the first embedding result in a batch is correct, but all subsequent results are a single incorrect fixed value.

**Comment by monatis** [comment]
@skirodev Thanks for raising the issue. I'll try to reproduce it. It might be related to a memory alignment issue that I would need to patch in the ggml repo. Will update it once I reproduce it.

**Comment by monatis** [comment]
#71

**Comment by skirodev** [comment]
This PR only fixed batch inference for the patch32 model, not for other patches (such as patch16 and patch14) model. Maybe we should keep it open. What's your take on this?
