### ISSUE TITLE
Memory leak: clip_tokenize and clip_image_preprocess

### ISSUE THREAD

**Issue by nemosupremo** [monatis/clip.cpp#86]
It looks like `clip_tokenize` and `clip_image_preprocess` both allocate arrays:

https://github.com/monatis/clip.cpp/blob/8f348725271db67517de871dea4a4e8a159e664f/clip.cpp#L721

https://github.com/monatis/clip.cpp/blob/8f348725271db67517de871dea4a4e8a159e664f/clip.cpp#675

however there is no way to free these arrays. I'm not sure if I'm missing something here with C++, but these methods should either provide a free or the ability to pass your own buffer.

**Comment by lithdew** [comment]
clip_image_u8_clean and clip_image_f32_clean frees these arrays.

**Comment by nemosupremo** [comment]
Looks like those functions were added a bit after I opened this issue.
