### ISSUE TITLE
Question about the CLIP model in clip.cpp and llama.cpp

### ISSUE THREAD

**Issue by lhr0909** [monatis/clip.cpp#87]
Hi,

I have been trying out the LLaVA models in llama.cpp and they work great! I am curious about the CLIP model and clip.cpp used in llama.cpp:

I would like to use the same CLIP model to encode texts and images from the CLIP models from LLaVA, but it seems like the source code in [llama.cpp](https://github.com/ggerganov/llama.cpp/blob/master/examples/llava/clip.cpp) does not have a way to encode text. I am curious if it is possible to add text encoding capabilities in the clip.cpp inside llama.cpp, or is it possible to load the LLaVA 's CLIP in clip.cpp and gain text encoding capabilities.

I hope this is not confusing and a right place to ask. Thank you for the great work!

**Comment by monatis** [comment]
the CLIP encoder in LLaVA does not include text-specific layers, so even if we port it to clip.cpp it wouldn't help with it. We have the plan to implement full support for the CLIP model in llama.cpp just as in clip.cpp, but I'm a little bit busy these days and hope to find some time to do so soon. Until then, I suggest compiling llama.cpp and clip.cpp separately to be able to use both.
