### ISSUE TITLE
Python Binding Example: AttributeError: dlsym(0x8ea2fac0, make_clip_image_u8): symbol not found

### ISSUE THREAD

**Issue by MotzWanted** [monatis/clip.cpp#94]
I'm testing the python binding from `./examples` on a Darwin arm64 (Apple Silicon M2) system. I run into an `AttributeError` in [line 202](https://github.com/monatis/clip.cpp/blob/f4ee24bb86680a27f83c8e8c70adbcf4cb776615/examples/python_bindings/clip_cpp/clip.py#L202) and again in [line 206](https://github.com/monatis/clip.cpp/blob/f4ee24bb86680a27f83c8e8c70adbcf4cb776615/examples/python_bindings/clip_cpp/clip.py#L206).

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/ctypes/__init__.py", line 389, in __getattr__
    func = self.__getitem__(name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/ctypes/__init__.py", line 394, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: dlsym(0x8ea2fac0, make_clip_image_u8): symbol not found
```
I compiled using these options:
```
cmake -DCMAKE_APPLE_SILICON_PROCESSOR=arm64 -DCLIP_NATIVE=ON -DBUILD_SHARED_LIBS=ON ..
```

Any help would be much appreciated 🙏 I'm new to cpp. @monatis

**Comment by MotzWanted** [comment]
I've solved the issue. I verify symbol export in the compiled library by using the `nm` tool on macOS:
```
nm -gU /path/to/libclip.dylib
```
I look for `make_clip_image_u8` and `make_clip_image_f32` in the output, and find similar functions named `_clip_image_u8_make` and `_clip_image_f32_make`. I change the naming in [line 202](https://github.com/monatis/clip.cpp/blob/f4ee24bb86680a27f83c8e8c70adbcf4cb776615/examples/python_bindings/clip_cpp/clip.py#L202) and [line 206](https://github.com/monatis/clip.cpp/blob/f4ee24bb86680a27f83c8e8c70adbcf4cb776615/examples/python_bindings/clip_cpp/clip.py#L206) which solves the `AttributeError`.

**Comment by monatis** [comment]
Thanks @MotzWanted. Currently I have limited time to provide support for this library, but I want to rewrite the Python bindings for a faster inference very soon. I'll test and verify it on different platforms then.

**Comment by MotzWanted** [comment]
No worries @monatis. Let me know if I can be of any help to you... Btw. can you tell me why you have marked out [clip_image_batch_encode](https://github.com/monatis/clip.cpp/blob/f4ee24bb86680a27f83c8e8c70adbcf4cb776615/examples/python_bindings/clip_cpp/clip.py#L193)?

**Comment by monatis** [comment]
During the first implementation of Python bindings, signatures of functions for batch processing were not compatible with ctypes --they were accepting a `std::vector` instead of a custom struct. I refactored it in the C/C++ code later on but didn't implement on the Python side. This will be fixed in the upcoming implementation.
